version: '3'
services:
  db:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: ./rails
    volumes:
      - ./rails:/mnt/rails
    working_dir: /mnt/rails
    env_file: .env
    command: 'sh -c "yarn install && bin/rails db:setup && bundle exec rails s -p 5000 -b 0.0.0.0"'
    ports:
      - "80:5000"
    links:
      - db
    depends_on:
      - db
volumes:
  postgres_data:
